### ISSUE TITLE
Show() destroys the image

### ISSUE THREAD

**Issue by ghost** [gkorepanov/smart-plot#11]
It shows blank image for the second `show()` call.

```python
In [1]: import smartplot
In [2]: smartplot.addplot()
<class 'statsmodels.iolib.table.SimpleTable'>
In [3]: smartplot.show()
In [4]: smartplot.show()
```

**Comment by gkorepanov** [comment]
That is how it is supposed to work since there is no "clear" method (probably It's not such a good concept)

**Comment by ghost** [comment]
Well, shouldn't it be implemented then?

**Comment by gkorepanov** [comment]
I believe so.

**Comment by gkorepanov** [comment]
I don't think we should close this, as introducing clear() will not solve a problem.
