### ISSUE TITLE
There should be well thought-out API for multiple plots

### ISSUE THREAD

**Issue by gkorepanov** [gkorepanov/smart-plot#13]
I believe restricting the user to use first few columns is a wrong idea. There should be some API like 
`using='1x, 2y, 3xerr'`

**Comment by ghost** [comment]
It should also provide plots fine-tuning (marker colors and types e.g.).

**Comment by ghost** [comment]
It"s now a main principle of new project branch *OOP* so it seems to be done soon in some way.
