### ISSUE TITLE
Refactor code, it's already ugly

### ISSUE THREAD

**Issue by gkorepanov** [gkorepanov/smart-plot#4]

**Comment by ghost** [comment]
Believe I have the opportunity to do so.

**Comment by ghost** [comment]
BTW, could you please label the issues in appropriate way? There are too much by time.

**Comment by gkorepanov** [comment]
Yeah, I will do that.

**Comment by gkorepanov** [comment]
I believe the concept OOP concept will best fit the requirements of that particular project, as we have multiple plots, they are the parts of a whole "canvas", and there are some settings plot-specific, and some are common
